version: 2.1

orbs:
  genymotion-saas: genymotion/genymotion-saas@dev:alpha

jobs:
  android5:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    steps:
      - checkout
      - run:
          name: Accept all SDK package licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies -PdisablePreDex
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "d39db595-6ae3-4ae9-bddc-fcaf85cf1d83"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  android6:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    steps:
      - checkout
      - run:
          name: Accept all SDK package licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies -PdisablePreDex
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "c660c8c2-df75-44ac-9a81-e08f468f1c10"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  android7:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    steps:
      - checkout
      - run:
          name: Accept all SDK package licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies -PdisablePreDex
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "9f1adea8-e280-460d-9319-580570f61e8c"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  android8:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    steps:
      - checkout
      - run:
          name: Accept all SDK package licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies -PdisablePreDex
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "c52fdfc2-6914-4266-aa6e-50258f50ef91"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  android81:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    steps:
      - checkout
      - run:
          name: Accept all SDK package licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies -PdisablePreDex
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "20ee73af-5c32-405c-8582-cd19ffd175c2"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  android9:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    steps:
      - checkout
      - run:
          name: Accept all SDK package licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies -PdisablePreDex
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "e20da1a3-313c-434a-9d43-7268b12fee08"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  android10:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    steps:
      - checkout
      - run:
          name: Accept all SDK package licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies -PdisablePreDex
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "70eaaf75-bd9a-406d-9f01-682a5d400c6e"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build:
    jobs:
      - "android5"
      - "android6"
      - "android7"
      - "android8"
      - "android81"
      - "android9"
      - "android10"
