version: 2.1
orbs:
  genymotion-saas: genymotion/genymotion-saas@1.0.0

workflows:
  build:
    jobs:
      - build:
          post-steps:
            - genymotion-saas/stop-instance

jobs:
  build:
    executor: genymotion-saas/default
    steps:
      - checkout
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "e20da1a3-313c-434a-9d43-7268b12fee08"
      - run: ./gradlew connectedDebugAndroidTest