version: 2.1

orbs:
  genymotion-saas: genymotion/genymotion-saas@0.1.0

defaults: &defaults
  docker:
      - image: circleci/android:api-29
  working_directory: ~/code
  environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Accept all SDK package licenses
          command: |
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;
      - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies -PdisablePreDex
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - persist_to_workspace:
          # The root of the workspace, here just the CWD
          root: .
          # The sub-paths of the workspace to persist
          paths:
            - .gradle
  android8:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "c52fdfc2-6914-4266-aa6e-50258f50ef91"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  android81:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "20ee73af-5c32-405c-8582-cd19ffd175c2"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  android9:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "e20da1a3-313c-434a-9d43-7268b12fee08"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  android10:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "70eaaf75-bd9a-406d-9f01-682a5d400c6e"
      - run:
          name: Run Expresso Android Tests
          command: |
            gmsaas instances list
            ./gradlew :app:connectedDebugAndroidTest -PdisablePreDex
      - genymotion-saas/stop-instance
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - android8:
          requires:
          - build
      - android81:
          requires:
          - build
      - android9:
          requires:
          - build
      - android10:
          requires:
          - build
