version: 2.1

orbs:
  genymotion-saas: genymotion/genymotion-saas@1.0.0

jobs:
  android9:
    executor: genymotion-saas/default
    steps:
      - checkout
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "35143f7e-a294-4e2e-b230-1a9d6f2d2bdc"
      - run: ./gradlew connectedDebugAndroidTest
      - genymotion-saas/stop-instance
  android10:
    executor: genymotion-saas/default
    steps:
      - checkout
      - genymotion-saas/setup
      - genymotion-saas/start-instance:
          recipe_uuid: "35143f7e-a294-4e2e-b230-1a9d6f2d2bdc"
      - run: ./gradlew connectedDebugAndroidTest 
      - genymotion-saas/stop-instance

workflows:
  version: 2
  build_and_test:
    jobs:
      - android9
      - android10
