version: 2.1

orbs:
  genymotion-saas: genymotion/genymotion-saas@dev:alpha

workflows:
  version: 2
  build:
    jobs:
      - genymotion-saas/run:
          steps:
            - run: adb devices && gmsaas instances list && ./gradlew connectedDebugAndroidTest
