version: 2.1

orbs:
  genymotion-saas: genymotion/genymotion-saas@dev:alpha

jobs:
  android9:
    executor: genymotion-saas/default
    steps:
      - genymotion-saas/setup:
          email: "${GMCLOUD_SAAS_EMAIL}"
          password: "${GMCLOUD_SAAS_PASSWORD}"
      - genymotion-saas/start-instance:
          recipe_uuid: "fb936099-d261-4dd3-8dec-3fc14f1d0f03"
          adb_serial_port: "12346"
      - genymotion-saas/stop-instance
  android8:
    executor: genymotion-saas/default
    steps:
      - genymotion-saas/setup:
          email: "${GMCLOUD_SAAS_EMAIL}"
          password: "${GMCLOUD_SAAS_PASSWORD}"
      - genymotion-saas/start-instance:
          recipe_uuid: "c52fdfc2-6914-4266-aa6e-50258f50ef91"
          adb_serial_port: "12345"
      - genymotion-saas/stop-instance

workflows:
  version: 2
  build:
    jobs:
      - "android9"
      - "android8"