version: 2.1

orbs:
  genymotion-saas: genymotion/genymotion-saas@1.0.0

defaults: &defaults
  executor: genymotion-saas/default
  working_directory: ~/code
  environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"

workflows:
  version: 2
  basic_workflow:
    jobs:
      - genymotion-saas/run_tests:
          name: "Run Android 9.0"
          recipe_uuid: 'd8b10016-c02a-41f9-8a91-ce9b44197d21'
          steps:
            - run: ./gradlew cAT
          
      - genymotion-saas/run_tests:
          name: "Run Android 10.0"
          recipe_uuid: '4c015ada-e64e-4f5d-a320-06cbf6e95648'
          adb_serial_port: 12345
          steps:
            - run: ./gradlew cAT
